<a href="https://colab.research.google.com/github/Tyo0010/TensorFlow_Course/blob/main/00_TensorFlow_Tyo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# in this notebook, we're going to cover some of the most fundmental concept of tensors using TensorFlow

More specifically, we're going to cover:
  * Introduction to tensors
  * Getting infromation from tensors
  * Manipulating tensors
  * Tensors and  NumPy
  * Using @tf.function (a way to speed up your regular Python funcetions)
  * Using GPUs with TensorFlow(or TPU)
  * Exercises to try for yourself!
  

## Introduction to Tensors

In [2]:
# import TenserFLow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimensions of vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
a_matrix = tf.constant([[10.,7.],
                        [3., 4.],
                        [6., 23.]], dtype=tf.float32) # specify the data types with dtype

a_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 6., 23.]], dtype=float32)>

In [10]:
# What's the number dimensions of a_matrix?
a_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we've created so far:
* Scalar: single numbers
* Vector: number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimentional array of number (when n can be any number, a 0-dimesional tensor is a scalar, 1-dimensional tensor is a vector)

# Creating tensors with 'tf.Variable'

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchengeable_tensor = tf.constant([10, 7])
changeable_tensor, unchengeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# # Let's try one of the elements in our unchangeable tensor
# unchengeable_tensor[0].assign(7)
# unchengeable_tensor

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [16]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape =(3,2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

 ### Shuffke the order of elements in a tensor


In [17]:
# Shuffle the tensor (variable for when you want to shuffle data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [41, 2],
                            [35, 1]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[41,  2],
       [35,  1],
       [10,  7]], dtype=int32)>

In [18]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(41)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[35,  1],
       [41,  2],
       [10,  7]], dtype=int32)>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [41,  2],
       [35,  1]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled, seed=(42))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[35,  1],
       [41,  2],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [21]:
#Create tensor of all ones
tf.ones([ 7, 3])

<tf.Tensor: shape=(7, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
# Create tensor of all zeros
tf.zeros([5, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)


In [23]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 50, dtype=np.int32) #create a numpy array from 1 to 25
numpy_A

# x = tf.constant(some_matrix) #capital for tensor or matrix
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape=(7,1,7))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(7, 1, 7), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19, 20, 21]],
 
        [[22, 23, 24, 25, 26, 27, 28]],
 
        [[29, 30, 31, 32, 33, 34, 35]],
 
        [[36, 37, 38, 39, 40, 41, 42]],
 
        [[43, 44, 45, 46, 47, 48, 49]]], dtype=int32)>,
 <tf.Tensor: shape=(49,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       dtype=int32)>)

### Getting information from tensors


When dealing with tensors you probably want to be aware of the following attributes:
*   Shape
*   Rank
*   Axis or dimesion
* Size



In [25]:
# Create a rank 4 tensors (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5], dtype=tf.int32)
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
# Get various attributr of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimension (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'int32'>
Number of dimension (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing tensor

Tensors can be indexed just like Python list

In [29]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [30]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [31]:
some_list[:1]

[1]

In [32]:
# Get the first element from each dimension from each index expect the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [33]:
# Create a rank 2 tensor (2 dimensions)
rank_2 = tf.constant([[10, 7],[3, 4]])
rank_2.shape, rank_2.ndim

(TensorShape([2, 2]), 2)

In [34]:
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [35]:
# Get the last item of each of row of our rank 2 tensor
rank_2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [36]:
# Add in extra dimension to our rank 2 tensor
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manupilating tensors (tensors operation)

**Basic operations**

`+`,`-`,`*`,`/`


In [38]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# Original tensor is unchaged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
# Multiplication also work
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
# Substraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [42]:
# We can use the tensorflow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication with tensor

In ML, matrix multiplication is one of the most common tensor operations.


There are two rules out tensors (or matrics) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. the resulting matrix has the shape of the outer dimension

In [43]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [45]:
tensor.shape

TensorShape([2, 2])

In [46]:
# Create a tensor (3, 2) tensor
x = tf.constant([[1, 2],[3, 4],[5, 6]])
y = tf.constant([[7, 8], [9, 10],[11, 12]])

In [50]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [49]:
# Let'schange shape of y
tf.reshape(y, shape=(2,3,1))

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]], dtype=int32)>

In [59]:
vec = tf.constant([2,3,4,5,6,7])
vec, tf.reshape(vec, shape=(1,2,3))

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[2, 3, 4],
         [5, 6, 7]]], dtype=int32)>)

In [61]:
# Try to multiply X by reshape Y
x @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(tf.reshape(x,shape=(2,3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [63]:
# Can do the same with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [64]:
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.malmul()`
* `tf.tensordot`
* `@`

In [65]:
# Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [66]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [67]:
# Perfom matrix multiplication x and y (reshaped)
tf.matmul(x,tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [68]:
# Check the values of y, reshape y and transposed y
print("Normal y:")
print(y,"\n")

print("y reshapes to (2,3):")
print(tf.reshape(y,shape=(2,3)), "\n")

print("y transposed:")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshapes to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [69]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to get satisfy the matrix multiplication rules

### Changing the datatype of a tensor

In [70]:
tf.__version__

'2.15.0'

In [71]:
# Create a new tensor with default data type (float32)
B = tf.constant([1.7, 3.2])
B.dtype

tf.float32

In [72]:
c = tf.constant([7, 10])
c.dtype

tf.int32

In [73]:
# Change float32 to float16 (reduce precision)
B = tf.cast(B, dtype=(tf.float16))
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.2], dtype=float16)>,
 tf.float16)

In [74]:
# Change from int32 to float32
e = tf.cast(c, dtype=(tf.float32))
e

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [75]:
e_16 = tf.cast(c, dtype=(tf.float16))
e_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensor

Aggregating tensors = condensing them from multiple calues down to a smaller amount values

In [76]:
# Get the absolute values
d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [77]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation
* Get the max
* Get the min
* Get the mean of tensor
* Get the sum of a tensor

In [78]:
# Create a randdom tensor with values between 0 and 100 of size 50
e = tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 68, 56, 72, 88, 51, 30, 42, 31, 25, 25, 84, 29, 20, 39, 10, 74,
       79, 89, 22, 41,  8, 39, 42, 27, 77, 32, 76, 50, 42, 62, 52, 20, 96,
        9, 23, 57, 75, 10, 86, 62, 49, 16, 40, 17, 43, 41, 88, 80, 65])>

In [79]:
tf.size(e), e.ndim, e.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [80]:
# Finding the min of tensor
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [81]:
# Find the max
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [82]:
# Find the mean
tf.reduce_mean(e)


<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [83]:
# Find the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2362>

In [89]:
# Find the variance
tf.math.reduce_variance(tf.cast(e, tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=656.3423999999999>

In [85]:
# Find the deviation
tf.math.reduce_std(tf.cast(e, tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=25.619180314756363>

In [95]:
import tensorflow_probability as tfp
tfp.stats.variance(e)
tfp.stats.stddev(tf.cast(e, tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=25.619180314756363>

###Find the positional max and min



In [103]:
# Create a new tensor for finding positional min and max
tf.random.set_seed(46)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
       0.39785516, 0.717703  , 0.8796133 , 0.41742086, 0.8905815 ,
       0.04490781, 0.64715993, 0.6124575 , 0.8963598 , 0.50094795,
       0.5403452 , 0.13583767, 0.796286  , 0.11443329, 0.6610137 ,
       0.75864327, 0.05791759, 0.9041784 , 0.5926819 , 0.14621067,
       0.10904384, 0.28547847, 0.65069926, 0.09890389, 0.7398746 ,
       0.56936777, 0.7675011 , 0.27471685, 0.72731483, 0.69775176,
       0.50558805, 0.98601305, 0.7327801 , 0.85814536, 0.04894578,
       0.02490926, 0.9485537 , 0.9631084 , 0.5954149 , 0.16012132,
       0.2517103 , 0.34919453, 0.16999745, 0.1833117 , 0.43756902],
      dtype=float32)>

In [105]:
# Find positinal max
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [104]:
# Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98601305>

In [99]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [100]:
# Check for equality
tf.reduce_max(f) == f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [101]:
# Find positional min
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [102]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [108]:
# Create tensor
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [109]:
g_squeezed = tf.squeeze(g)
g_squeezed, g_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))